# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-09-12 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0002_auto_20170912_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='img',
            field=models.CharField(default='', max_length=100),
        ),
    ]
